name: back-a-deux-pas CI with Maven and Docker
# Triggers the workflow on push or pull request
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  maven:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ["21"]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Use a pre-defined action called 'checkout' to retrieve the source code from the repository
      - uses: actions/checkout@v4
      # Configure the Java environment and enable Maven caching to accelerate subsequent build executions
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven
      # Get application version from pom.xml to variable
      - name: Retrieve Application Version
        run: |
          echo "APP_VERSION=$(mvn -f pom.xml help:evaluate -Dexpression='project.version' -q -DforceStdout) ">> $GITHUB_ENV
      - name: Print Maven POM project version
        run: echo "application version = ${{ env.APP_VERSION }}"
      # Project compilation
      - name: Compile Code Source
        run: mvn -B clean compile
      # Execution of unit tests
      - name: Run Unit Tests
        run: mvn -B test
      # Package application
      - name: Package Application
        run: mvn -B package -Dmaven.test.skip=true
      # Upload artifact to repository
      - name: Upload Application Package
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.APP_NAME }}-${{ env.APP_VERSION }}.jar
          path: ${{ github.workspace }}/target/${{ env.APP_NAME }}-${{ env.APP_VERSION }}.jar
  docker:
    if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3
      # Build docker image and push to docker hub
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: douniabed/${{ env.APP_NAME }}:${{ env.APP_VERSION }}
