# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

name: Java CI with Maven
# Triggers the workflow on push or pull request
on:
  push:
    branches: [ "dev, main" ]
  pull_request:
    branches: [ "dev, main" ]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Use a pre-defined action called 'checkout' to retrieve the source code from the repository
    - uses: actions/checkout@v3
    # Configure the Java environment and enable Maven caching to accelerate subsequent build executions
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    # Project compilation with Maven and creation of the package from the pom.xml file
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    # Execution of unit tests
    - name: Run Unit Tests
      run: mvn test
